version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ben
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: places_annotations_${APP_ENV:-development}
    volumes:
      - ./data/postgres/${APP_ENV:-development}:/var/lib/postgresql/data
      - .:/app
    ports:
      - 65432:5432

  appserver:
    image: "benbergstein/places-annotations:latest"
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      GOOGLE_API_KEY:
      DATABASE_HOST: db
      DATABASE_POST: 5432
    depends_on:
      - db

  test:
    image: "benbergstein/places-annotations:latest"
    entrypoint: ["lein", "test"]

    environment:
      APP_ENV:
      GOOGLE_API_KEY:
      DATABASE_HOST: db
      DATABASE_POST: 5432
    depends_on:
      - db

